## EXTENSION REST CLIENT ##

### Traer todas las camisetas
GET https://6aab1be4ea0e22daa6dbcb90.mockapi.io/api/productos

### Traer una camiseta
GET https://6aab1be4ea0e22daa6dbcb90.mockapi.io/api/productos/platense-2024-titular